# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97835f48f7c85082e3d684672c57d60f"
name = "test-django-app"
handle = "test-django-app-8"
application_url = "https://murray-denial-berlin-acts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "koko-flow-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://murray-denial-berlin-acts.trycloudflare.com/auth/callback",
  "https://murray-denial-berlin-acts.trycloudflare.com/auth/shopify/callback",
  "https://murray-denial-berlin-acts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
